version: "3.8"

services:
  api-gateway:
    build: ./apps/api-gateway
    container_name: api-gateway
    env_file:
      - ./apps/api-gateway/.env.development
    ports:
      - "4000:4000"
    depends_on:
      - whatsapp_delivery_users
      - whatsap_delivery_payment
  whatsapp_delivery_users:
    build: .
    container_name: whatsapp_delivery_users
    command: [ "npm", "run", "start:users:prod" ]
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      USER_MAIN_DATABASE_URI: mongodb://root:password@mongodb:27017/whatsapp_delivery_users?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules

  whatsap_delivery_payment:
    build: .
    container_name: whatsap_delivery_payment
    command: [ "npm", "run", "start:payment:prod" ]
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      USER_MAIN_DATABASE_URI: mongodb://root:password@mongodb:27017/whatsapp_delivery_payment?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:7
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  krakend:
    image: krakend:2.9
    container_name: krakend_gateway
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: [ "run", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - whatsapp_delivery_users
      - whatsap_delivery_payment

volumes:
  mongo_data:
